### PR TITLE
Moving frameworks to utils folder

### PR DESCRIPTION
**Pull request by faisaltheparttimecoder**
# Moving framework to utils folder

The go files below are moved to the utils folder.

+ db.go

Done as part of the issue : https://github.com/pivotal-gss/gpmt2/issues/8

# Migrated from go-logging to logrus

+ Removed go-logging dependency
+ Created a wrapper package using logrus.

### CODE REVIEW

**Comment by tylarb** [comment]
@faisaltheparttimecoder  see my recent issue #10 - I think logging should be globally initialized, then set in cmd. That should be possible. If it can't be done with go-logging, it was working with logrus and we can toy with the formatting separately. 

Setting logging globally should allow us to just import the logger package and then call log with the write to filesystem and stdout handled easily.

We might need to take good time to organize this, but the root structure should allow the rest of the project to be more maintianable.

**Comment by faisaltheparttimecoder** [comment]
@Tylarb Yes that can be done, when you push your ssh utils just move that out to the root folder. or you want I can push that one now ? what you think ?

**Comment by tylarb** [comment]
@faisaltheparttimecoder  With go-logging, can we just call logging.debug in any sub-package as expected? That was one reason I started with Logrus, because you can import it as log and all configuration will be inherited. 

If so, we can merge this then I can adjust. If not, let's hold off on this PR, get logrus working from package main, then continue from there.

**Comment by faisaltheparttimecoder** [comment]
The way go-logging works is 

+ you setup a logger name.
+ then from any package ( on any file ) just call that logger like 

```
log = logging.MustGetLogger(utils.ToolName)
```

and then any logging works as normal with go-logging format, you can see the example on the root.go file from the "cmd" package.

**Review by tylarb — APPROVED** [review]
I'm going to merge this to maintain the db code, etc, then refractor significantly.

I hope this to be the last/only major refractor of the project.

**Pull request merged**
